version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8e:15:e9:4d:9a:13:2c:0d:f7:b8:fc:43:c1:c0:ab:b6"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
